apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  workspaces:
    - name: source
  steps:
    - name: nose
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        pip install -r requirements.txt
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=service
    - name: cleanup
      image: alpine:latest
      script: |
        rm -rf $(workspaces.source.path)/*
